name: Deploy EC2

on:
  push:
    branches:
      - main

jobs:
  deploy:
    name: Deploy
    runs-on: ubuntu-latest
    
    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Deploy to EC2
        uses: easingthemes/ssh-deploy@main
        with:
          SCRIPT_BEFORE: ${{ secrets.SCRIPT_BEFORE }}
          SCRIPT_AFTER: ${{ secrets.SCRIPT_AFTER }}
          REMOTE_USER: ${{ secrets.USERNAME }}
          SSH_PRIVATE_KEY: ${{ secrets.SSH_PRIVATE_KEY }}
          REMOTE_HOST: ${{ secrets.HOST }}
          TARGET: ${{ secrets.TARGET }}