name: Deploy EC2

on: [push]

jobs:
  deploy:
    name: Deploy
    runs-on: ubuntu-latest
    
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      # - name: Deploy to EC2
      #   uses: appleboy/ssh-action@v1.0.0
      #   with:
      #       host: ${{ secrets.HOST }}
      #       username: ${{ secrets.USERNAME }}
      #       key: ${{ secrets.SSH_PRIVATE_KEY }}
      #       port: ${{ secrets.PORT }}
      #       script: |
      #         cd /var/www/hotel-miranda-laravel
      #         sudo chown -R ubuntu:ubuntu /var/www/hotel-miranda-laravel
      #         sudo git pull
      #         composer install
      #         php artisan migrate:refresh
      #         sudo chown -R www-data:www-data /var/www/hotel-miranda-laravel
      #         sudo systemctl restart apache2

      - name: Deploy to Server
        uses: easingthemes/ssh-deploy@main
        with:
          SCRIPT_BEFORE: "sudo chown -R ubuntu:ubuntu /var/www/hotel-miranda-laravel/"
          SCRIPT_AFTER: "sudo chown -R www-data:www-data /var/www/hotel-miranda-laravel/"
          SSH_PRIVATE_KEY: ${{ secrets.SSH_PRIVATE_KEY }}
          REMOTE_HOST: "ec2-13-39-50-47.eu-west-3.compute.amazonaws.com"
          REMOTE_USER: "ubuntu"
          TARGET: "/var/www/hotel-miranda-laravel/"