name: Deploy EC2

on: [push]

jobs:
  deploy:
    name: Deploy
    runs-on: ubuntu-latest
    
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Deploy to EC2
        uses: appleboy/ssh-action@v1.0.0
        with:
            host: ${{ secrets.HOST }}
            username: ${{ secrets.USERNAME }}
            key: ${{ secrets.SSH_PRIVATE_KEY }}
            port: ${{ secrets.PORT }}
            script: |
              cd /var/www/hotel-miranda-laravel
              git config --global user.email "sio.gaspar@gmail.com"
              git config --global user.name "GasparSio"
              sudo chown -R ubuntu:ubuntu /var/www/hotel-miranda-laravel
              sudo git pull
              composer install
              php artisan migrate:refresh
              sudo chown -R www-data:www-data /var/www/hotel-miranda-laravel
              sudo systemctl restart apache2